In [1]:
import pandas as pd

In [8]:
df_hotel = pd.read_csv("reservas_hoteleras.csv")

df_hotel

,ID_Reserva,Destino,Tipo_Habitacion,Tipo_Huesped,Precio_Noche,Noches_Estadia,Gasto_Adicional,Estado_Reserva
0,RES-7001,Manizales,Estándar,Extranjero,250000.0,8,80000.0,Completada
1,RES-7002,Santa Rosa de Cabal,Estándar,Extranjero,120000.0,9,150000.0,Completada
2,RES-7003,Manizales,Estándar,Extranjero,180000.0,6,230000.0,Completada
3,RES-7004,Santa Rosa de Cabal,Glamping,Nacional,450000.0,8,80000.0,Completada
4,RES-7005,Salamina,Suite,Nacional,250000.0,7,80000.0,Completada
...,...,...,...,...,...,...,...,...
1007,RES-7128,Salamina,Cabaña Campestre,Nacional,450000.0,2,0.0,Cancelada
1008,RES-7129,Salamina,Glamping,Extranjero,180000.0,2,150000.0,Completada
1009,RES-7130,Salamina,Suite,Extranjero,NaN,11,150000.0,Completada
1010,RES-7131,Salamina,Estándar,Nacional,450000.0,11,150000.0,Cancelada
1011,RES-7132,Salamina,Estándar,Nacional,120000.0,8,80000.0,Completada

In [ ]:
#se extrajo la colimna tipo_habitacion
t_habitacion = df_hotel["Tipo_Habitacion"]

t_habitacion

0               Estándar
1               Estándar
2               Estándar
3               Glamping
4                  Suite
              ...
1007    Cabaña Campestre
1008            Glamping
1009               Suite
1010            Estándar
1011            Estándar
Name: Tipo_Habitacion, Length: 1012, dtype: str

In [ ]:
#se extrajo la columna tipo_huesped y precio_noche
tabla_sel = df_hotel[["Tipo_Huesped", "Precio_Noche"]]

tabla_sel

     Tipo_Huesped  Precio_Noche
0      Extranjero      250000.0
1      Extranjero      120000.0
2      Extranjero      180000.0
3        Nacional      450000.0
4        Nacional      250000.0
...           ...           ...
1007     Nacional      450000.0
1008   Extranjero      180000.0
1009   Extranjero           NaN
1010     Nacional      450000.0
1011     Nacional      120000.0

[1012 rows x 2 columns]

In [ ]:
#buca por etiqueta
df_hotel.loc[[210]]

,ID_Reserva,Destino,Tipo_Habitacion,Tipo_Huesped,Precio_Noche,Noches_Estadia,Gasto_Adicional,Estado_Reserva
210,RES-7211,Santa Rosa de Cabal,Cabaña Campestre,Nacional,250000.0,9,45000.0,Completada

In [17]:
# identifica duplicados
print("duplocados:", df_hotel .duplicated().sum())

df_hotel [df_hotel.duplicated()]

duplocados: 12

,ID_Reserva,Destino,Tipo_Habitacion,Tipo_Huesped,Precio_Noche,Noches_Estadia,Gasto_Adicional,Estado_Reserva
1000,RES-7121,Filandia,Glamping,Nacional,180000.0,2,45000.0,Cancelada
1001,RES-7122,Manizales,Estándar,Nacional,180000.0,8,80000.0,Completada
1002,RES-7123,Salento,Suite,Nacional,120000.0,8,350000.0,Cancelada
1003,RES-7124,Santa Rosa de Cabal,Suite,Nacional,120000.0,9,80000.0,Completada
1004,RES-7125,Filandia,Estándar,Nacional,120000.0,3,150000.0,Completada
1005,RES-7126,Salamina,Estándar,Nacional,250000.0,9,150000.0,Completada
1006,RES-7127,Manizales,Suite,Extranjero,120000.0,11,0.0,Completada
1007,RES-7128,Salamina,Cabaña Campestre,Nacional,450000.0,2,0.0,Cancelada
1008,RES-7129,Salamina,Glamping,Extranjero,180000.0,2,150000.0,Completada
1009,RES-7130,Salamina,Suite,Extranjero,NaN,11,150000.0,Completada
1010,RES-7131,Salamina,Estándar,Nacional,450000.0,11,150000.0,Cancelada
1011,RES-7132,Salamina,Estándar,Nacional,120000.0,8,80000.0,Completada

In [20]:
# eliminar duplicados 
df_sin_duplicados = df_hotel.drop_duplicates()
df_sin_duplicados

,ID_Reserva,Destino,Tipo_Habitacion,Tipo_Huesped,Precio_Noche,Noches_Estadia,Gasto_Adicional,Estado_Reserva
0,RES-7001,Manizales,Estándar,Extranjero,250000.0,8,80000.0,Completada
1,RES-7002,Santa Rosa de Cabal,Estándar,Extranjero,120000.0,9,150000.0,Completada
2,RES-7003,Manizales,Estándar,Extranjero,180000.0,6,230000.0,Completada
3,RES-7004,Santa Rosa de Cabal,Glamping,Nacional,450000.0,8,80000.0,Completada
4,RES-7005,Salamina,Suite,Nacional,250000.0,7,80000.0,Completada
...,...,...,...,...,...,...,...,...
995,RES-7996,Filandia,Glamping,Nacional,320000.0,5,230000.0,Cancelada
996,RES-7997,Manizales,Estándar,Extranjero,320000.0,8,150000.0,Completada
997,RES-7998,Santa Rosa de Cabal,Glamping,Extranjero,250000.0,1,45000.0,Completada
998,RES-7999,Salento,Glamping,Extranjero,120000.0,8,45000.0,Completada
999,RES-8000,Santa Rosa de Cabal,Suite,Corporativo,600000.0,11,0.0,Cancelada

In [22]:
# filtro boleano reservas 
mascara = df_hotel["Noches_Estadia"] > 5
t_habitacion_critico = df_hotel[mascara]
t_habitacion_critico

,ID_Reserva,Destino,Tipo_Habitacion,Tipo_Huesped,Precio_Noche,Noches_Estadia,Gasto_Adicional,Estado_Reserva
0,RES-7001,Manizales,Estándar,Extranjero,250000.0,8,80000.0,Completada
1,RES-7002,Santa Rosa de Cabal,Estándar,Extranjero,120000.0,9,150000.0,Completada
2,RES-7003,Manizales,Estándar,Extranjero,180000.0,6,230000.0,Completada
3,RES-7004,Santa Rosa de Cabal,Glamping,Nacional,450000.0,8,80000.0,Completada
4,RES-7005,Salamina,Suite,Nacional,250000.0,7,80000.0,Completada
...,...,...,...,...,...,...,...,...
1005,RES-7126,Salamina,Estándar,Nacional,250000.0,9,150000.0,Completada
1006,RES-7127,Manizales,Suite,Extranjero,120000.0,11,0.0,Completada
1009,RES-7130,Salamina,Suite,Extranjero,NaN,11,150000.0,Completada
1010,RES-7131,Salamina,Estándar,Nacional,450000.0,11,150000.0,Cancelada
1011,RES-7132,Salamina,Estándar,Nacional,120000.0,8,80000.0,Completada

In [30]:
#recuperar reservas 
df_hotel[df_hotel["Destino"].isin(["salento", "filandia"])]

Empty DataFrame
Columns: [ID_Reserva, Destino, Tipo_Habitacion, Tipo_Huesped, Precio_Noche, Noches_Estadia, Gasto_Adicional, Estado_Reserva]
Index: []

In [34]:
# Filtro con .between
df_hotel[df_hotel["Precio_Noche"].between(180000.0 , 320000.0)]

,ID_Reserva,Destino,Tipo_Habitacion,Tipo_Huesped,Precio_Noche,Noches_Estadia,Gasto_Adicional,Estado_Reserva
0,RES-7001,Manizales,Estándar,Extranjero,250000.0,8,80000.0,Completada
2,RES-7003,Manizales,Estándar,Extranjero,180000.0,6,230000.0,Completada
4,RES-7005,Salamina,Suite,Nacional,250000.0,7,80000.0,Completada
6,RES-7007,Filandia,Glamping,Extranjero,180000.0,8,150000.0,Completada
9,RES-7010,Filandia,Glamping,Extranjero,180000.0,3,350000.0,Cancelada
...,...,...,...,...,...,...,...,...
997,RES-7998,Santa Rosa de Cabal,Glamping,Extranjero,250000.0,1,45000.0,Completada
1000,RES-7121,Filandia,Glamping,Nacional,180000.0,2,45000.0,Cancelada
1001,RES-7122,Manizales,Estándar,Nacional,180000.0,8,80000.0,Completada
1005,RES-7126,Salamina,Estándar,Nacional,250000.0,9,150000.0,Completada
1008,RES-7129,Salamina,Glamping,Extranjero,180000.0,2,150000.0,Completada

In [38]:
# Consulta con .query
df_hotel.query("Tipo_Huesped == 'Extranjero' and Estado_Reserva == 'Completada'")

,ID_Reserva,Destino,Tipo_Habitacion,Tipo_Huesped,Precio_Noche,Noches_Estadia,Gasto_Adicional,Estado_Reserva
0,RES-7001,Manizales,Estándar,Extranjero,250000.0,8,80000.0,Completada
1,RES-7002,Santa Rosa de Cabal,Estándar,Extranjero,120000.0,9,150000.0,Completada
2,RES-7003,Manizales,Estándar,Extranjero,180000.0,6,230000.0,Completada
5,RES-7006,Filandia,Suite,Extranjero,450000.0,3,45000.0,Completada
6,RES-7007,Filandia,Glamping,Extranjero,180000.0,8,150000.0,Completada
...,...,...,...,...,...,...,...,...
997,RES-7998,Santa Rosa de Cabal,Glamping,Extranjero,250000.0,1,45000.0,Completada
998,RES-7999,Salento,Glamping,Extranjero,120000.0,8,45000.0,Completada
1006,RES-7127,Manizales,Suite,Extranjero,120000.0,11,0.0,Completada
1008,RES-7129,Salamina,Glamping,Extranjero,180000.0,2,150000.0,Completada
1009,RES-7130,Salamina,Suite,Extranjero,NaN,11,150000.0,Completada

In [39]:
# Filtrar reservas cuyo destino comience con "S"

df_hotel[
    (df_hotel['Destino'].str.startswith('S')) &
    (df_hotel['Precio_Noche'] > 200000)
]

,ID_Reserva,Destino,Tipo_Habitacion,Tipo_Huesped,Precio_Noche,Noches_Estadia,Gasto_Adicional,Estado_Reserva
3,RES-7004,Santa Rosa de Cabal,Glamping,Nacional,450000.0,8,80000.0,Completada
4,RES-7005,Salamina,Suite,Nacional,250000.0,7,80000.0,Completada
15,RES-7016,Santa Rosa de Cabal,Estándar,Nacional,600000.0,1,45000.0,Completada
16,RES-7017,Salamina,Estándar,Nacional,600000.0,7,45000.0,Completada
21,RES-7022,Salento,Cabaña Campestre,Nacional,320000.0,9,80000.0,No Show
...,...,...,...,...,...,...,...,...
997,RES-7998,Santa Rosa de Cabal,Glamping,Extranjero,250000.0,1,45000.0,Completada
999,RES-8000,Santa Rosa de Cabal,Suite,Corporativo,600000.0,11,0.0,Cancelada
1005,RES-7126,Salamina,Estándar,Nacional,250000.0,9,150000.0,Completada
1007,RES-7128,Salamina,Cabaña Campestre,Nacional,450000.0,2,0.0,Cancelada
1010,RES-7131,Salamina,Estándar,Nacional,450000.0,11,150000.0,Cancelada

In [40]:
# Reemplazar los valores faltantes por el promedio
df_hotel['Precio_Noche'] = df_hotel['Precio_Noche'].fillna(
    df_hotel['Precio_Noche'].mean()
)

# Crear la columna Costo_Hospedaje
df_hotel['Costo_Hospedaje'] = (
    df_hotel['Precio_Noche'] * df_hotel['Noches_Estadia']
)

# Mostrar los resultados
df_hotel.head()

,ID_Reserva,Destino,Tipo_Habitacion,Tipo_Huesped,Precio_Noche,Noches_Estadia,Gasto_Adicional,Estado_Reserva,Costo_Hospedaje
0,RES-7001,Manizales,Estándar,Extranjero,250000.0,8,80000.0,Completada,2000000.0
1,RES-7002,Santa Rosa de Cabal,Estándar,Extranjero,120000.0,9,150000.0,Completada,1080000.0
2,RES-7003,Manizales,Estándar,Extranjero,180000.0,6,230000.0,Completada,1080000.0
3,RES-7004,Santa Rosa de Cabal,Glamping,Nacional,450000.0,8,80000.0,Completada,3600000.0
4,RES-7005,Salamina,Suite,Nacional,250000.0,7,80000.0,Completada,1750000.0

In [41]:
# Definir una función para calcular el costo del hospedaje
def calcular_costo(fila):
    return fila['Precio_Noche'] * fila['Noches_Estadia']

# Aplicar la función y crear una nueva columna
df_hotel['Costo_Hospedaje'] = df_hotel.apply(
    calcular_costo, axis=1
)

# Mostrar los resultados
df_hotel.head()

,ID_Reserva,Destino,Tipo_Habitacion,Tipo_Huesped,Precio_Noche,Noches_Estadia,Gasto_Adicional,Estado_Reserva,Costo_Hospedaje
0,RES-7001,Manizales,Estándar,Extranjero,250000.0,8,80000.0,Completada,2000000.0
1,RES-7002,Santa Rosa de Cabal,Estándar,Extranjero,120000.0,9,150000.0,Completada,1080000.0
2,RES-7003,Manizales,Estándar,Extranjero,180000.0,6,230000.0,Completada,1080000.0
3,RES-7004,Santa Rosa de Cabal,Glamping,Nacional,450000.0,8,80000.0,Completada,3600000.0
4,RES-7005,Salamina,Suite,Nacional,250000.0,7,80000.0,Completada,1750000.0

In [42]:
# Renombrar las columnas
df_hotel = df_hotel.rename(columns={
    'Tipo_Habitacion': 'Habitacion',
    'Estado_Reserva': 'Estado'
})

# Reordenar las columnas
df_hotel = df_hotel[
    [
        'ID_Reserva',
        'Destino',
        'Habitacion',
        'Tipo_Huesped',
        'Precio_Noche',
        'Noches_Estadia',
        'Gasto_Adicional',
        'Estado',
        'Costo_Hospedaje'
    ]
]

# Mostrar la tabla reorganizada
df_hotel.head()

,ID_Reserva,Destino,Habitacion,Tipo_Huesped,Precio_Noche,Noches_Estadia,Gasto_Adicional,Estado,Costo_Hospedaje
0,RES-7001,Manizales,Estándar,Extranjero,250000.0,8,80000.0,Completada,2000000.0
1,RES-7002,Santa Rosa de Cabal,Estándar,Extranjero,120000.0,9,150000.0,Completada,1080000.0
2,RES-7003,Manizales,Estándar,Extranjero,180000.0,6,230000.0,Completada,1080000.0
3,RES-7004,Santa Rosa de Cabal,Glamping,Nacional,450000.0,8,80000.0,Completada,3600000.0
4,RES-7005,Salamina,Suite,Nacional,250000.0,7,80000.0,Completada,1750000.0

In [43]:
# Agrupar por destino turístico
resumen_destinos = df_hotel.groupby('Destino').agg(
    Precio_Promedio=('Precio_Noche', 'mean'),
    Total_Costo_Hospedaje=('Costo_Hospedaje', 'sum')
)

# Mostrar los resultados
print(resumen_destinos)

                     Precio_Promedio  Total_Costo_Hospedaje
Destino
Filandia               241508.997086           3.086146e+08
Manizales              257005.003300           3.427835e+08
Salamina               250300.322950           3.401625e+08
Salento                259152.047119           2.912031e+08
Santa Rosa de Cabal    260676.949231           3.931237e+08

In [44]:
# Definir una función para calcular el rango
def calcular_rango(serie):
    return serie.max() - serie.min()

# Agrupar por tipo de habitación y calcular las métricas
dispersion = df_hotel.groupby('Habitacion').agg(
    Rango_Precio=('Precio_Noche', calcular_rango),
    Desviacion_Precio=('Precio_Noche', 'std'),
    Rango_Noches=('Noches_Estadia', calcular_rango),
    Desviacion_Noches=('Noches_Estadia', 'std')
)

# Mostrar los resultados
print(dispersion)

                  Rango_Precio  Desviacion_Precio  Rango_Noches  \
Habitacion
Cabaña Campestre      480000.0      124286.036190            11
Estándar              480000.0      129287.341440            11
Glamping              480000.0      114865.771819            11
Suite                 480000.0      118178.253856            11

                  Desviacion_Noches
Habitacion
Cabaña Campestre           3.515265
Estándar                   3.376516
Glamping                   3.388584
Suite                      3.483907

In [45]:
# Definir una función para calcular el rango
def calcular_rango(serie):
    return serie.max() - serie.min()

# Agrupar por tipo de habitación y calcular las métricas
dispersion = df_hotel.groupby('Habitacion').agg(
    Rango_Precio=('Precio_Noche', calcular_rango),
    Desviacion_Precio=('Precio_Noche', 'std'),
    Rango_Noches=('Noches_Estadia', calcular_rango),
    Desviacion_Noches=('Noches_Estadia', 'std')
)

# Mostrar los resultados
print(dispersion)

                  Rango_Precio  Desviacion_Precio  Rango_Noches  \
Habitacion
Cabaña Campestre      480000.0      124286.036190            11
Estándar              480000.0      129287.341440            11
Glamping              480000.0      114865.771819            11
Suite                 480000.0      118178.253856            11

                  Desviacion_Noches
Habitacion
Cabaña Campestre           3.515265
Estándar                   3.376516
Glamping                   3.388584
Suite                      3.483907

In [46]:
# Agrupar por destino y tipo de habitación
resumen_multivariable = df_hotel.groupby(
    ['Destino', 'Habitacion']
).agg(
    Promedio_Noches=('Noches_Estadia', 'mean'),
    Total_Costo_Hospedaje=('Costo_Hospedaje', 'sum')
)

# Mostrar los resultados
print(resumen_multivariable)

                                      Promedio_Noches  Total_Costo_Hospedaje
Destino             Habitacion
Filandia            Cabaña Campestre         6.250000           7.262135e+07
                    Estándar                 5.590909           5.836187e+07
                    Glamping                 7.122807           9.556135e+07
                    Suite                    6.652174           8.207000e+07
Manizales           Cabaña Campestre         6.152542           9.034612e+07
                    Estándar                 6.423077           8.711090e+07
                    Glamping                 6.591837           7.868844e+07
                    Suite                    6.172414           8.663806e+07
Salamina            Cabaña Campestre         6.232558           6.199948e+07
                    Estándar                 7.419355           1.186023e+08
                    Glamping                 5.727273           6.125709e+07
                    Suite                    6.912281           9.830366e+07
Salento             Cabaña Campestre         6.029412           5.268567e+07
                    Estándar                 5.948276           9.079747e+07
                    Glamping                 5.736842           5.309470e+07
                    Suite                    6.961538           9.462522e+07
Santa Rosa de Cabal Cabaña Campestre         7.350877           1.153699e+08
                    Estándar                 7.017857           1.000100e+08
                    Glamping                 6.822222           8.084709e+07
                    Suite                    7.207547           9.689664e+07